/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminOrderIdRouteImport } from './routes/admin.$orderId'
import { Route as OrderProductRouteImport } from './routes/order.$product'
import { Route as OrderSuccessRouteImport } from './routes/order.success'
import { Route as PayCheckoutIdRouteImport } from './routes/pay.$checkoutId'
import { Route as ApiFilesIdRouteImport } from './routes/api/files/$id'
import { Route as ApiOperatorSplatRouteImport } from './routes/api/operator/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderIdRoute = AdminOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const OrderProductRoute = OrderProductRouteImport.update({
  id: '/order/$product',
  path: '/order/$product',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order/success',
  path: '/order/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCheckoutIdRoute = PayCheckoutIdRouteImport.update({
  id: '/pay/$checkoutId',
  path: '/pay/$checkoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorSplatRoute = ApiOperatorSplatRouteImport.update({
  id: '/api/operator/$',
  path: '/api/operator/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avatar': typeof AvatarRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/$orderId': typeof AdminOrderIdRoute
  '/order/$product': typeof OrderProductRoute
  '/order/success': typeof OrderSuccessRoute
  '/pay/$checkoutId': typeof PayCheckoutIdRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/operator/$': typeof ApiOperatorSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avatar': typeof AvatarRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/$orderId': typeof AdminOrderIdRoute
  '/order/$product': typeof OrderProductRoute
  '/order/success': typeof OrderSuccessRoute
  '/pay/$checkoutId': typeof PayCheckoutIdRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/operator/$': typeof ApiOperatorSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avatar': typeof AvatarRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/$orderId': typeof AdminOrderIdRoute
  '/order/$product': typeof OrderProductRoute
  '/order/success': typeof OrderSuccessRoute
  '/pay/$checkoutId': typeof PayCheckoutIdRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/operator/$': typeof ApiOperatorSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avatar'
    | '/privacy'
    | '/terms'
    | '/admin/$orderId'
    | '/order/$product'
    | '/order/success'
    | '/pay/$checkoutId'
    | '/api/files/$id'
    | '/api/operator/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avatar'
    | '/privacy'
    | '/terms'
    | '/admin/$orderId'
    | '/order/$product'
    | '/order/success'
    | '/pay/$checkoutId'
    | '/api/files/$id'
    | '/api/operator/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avatar'
    | '/privacy'
    | '/terms'
    | '/admin/$orderId'
    | '/order/$product'
    | '/order/success'
    | '/pay/$checkoutId'
    | '/api/files/$id'
    | '/api/operator/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvatarRoute: typeof AvatarRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  OrderProductRoute: typeof OrderProductRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PayCheckoutIdRoute: typeof PayCheckoutIdRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
  ApiOperatorSplatRoute: typeof ApiOperatorSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$orderId': {
      id: '/admin/$orderId'
      path: '/$orderId'
      fullPath: '/admin/$orderId'
      preLoaderRoute: typeof AdminOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order/$product': {
      id: '/order/$product'
      path: '/order/$product'
      fullPath: '/order/$product'
      preLoaderRoute: typeof OrderProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/success': {
      id: '/order/success'
      path: '/order/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$checkoutId': {
      id: '/pay/$checkoutId'
      path: '/pay/$checkoutId'
      fullPath: '/pay/$checkoutId'
      preLoaderRoute: typeof PayCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/$': {
      id: '/api/operator/$'
      path: '/api/operator/$'
      fullPath: '/api/operator/$'
      preLoaderRoute: typeof ApiOperatorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOrderIdRoute: typeof AdminOrderIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrderIdRoute: AdminOrderIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvatarRoute: AvatarRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  OrderProductRoute: OrderProductRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PayCheckoutIdRoute: PayCheckoutIdRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
  ApiOperatorSplatRoute: ApiOperatorSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
